### ISSUE TITLE
Can´t compile

### ISSUE THREAD

**Issue by DeadlyTurtle** [tanc7/EXOCET-AV-Evasion#2]
Hello. I can generate the go file, but the program can't find some files in order to compile to an windows exe. Please look image for error:
![compile](https://user-images.githubusercontent.com/78433812/111085880-3754eb00-84f8-11eb-88e3-f3e7d0fd53c9.PNG)

**Comment by tanc7** [comment]
You will need to use the go get command against the GitHub path to install the module locally so you can compile the go file
