### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Chomikmarkus** [tanc7/EXOCET-AV-Evasion#5]
When trying to get source with 
root@vps158041:~# go get github.com/tanc7/EXOCET-AV-Evasiongo get github.com/tanc7/EXOCET-AV-Evasion: no matching versions for query "upgrade"
root@vps158041:~#

**Comment by tanc7** [comment]
What version of Golang do you have? Type `go version`

**Comment by Chomikmarkus** [comment]
go1.13.8

**Comment by Chomikmarkus** [comment]
But i got it to work now so , thanks gonna test it!

**Comment by Chomikmarkus** [comment]
Sry buddy need to reopen that;)
Golang compiles now binary from go get command, so after go get exocet i get executable 
EXOCET-AV-EVASION
Everything works well when i generate outputmalware.go file, until i recompile it back to executable i run into 
root@vps158041:~/go/bin# env GOARCH=amd64 GOOS=windows go build outputmalware.go
outputmalware.go:12:2: cannot find package "github.com/amenz
hinsky/go-memexec" in any of:
        /usr/lib/go-1.13/src/github.com/amenzhinsky/go-memex
ec (from $GOROOT)
        /root/go/src/github.com/amenzhinsky/go-memexec (from
 $GOPATH)

What version of go you were using? It seems very interesting project, would like to try it out

**Comment by Chomikmarkus** [comment]
So reinstalled manually 
https://github.com/amenzhinsky/go-memexec
and voila i have my executable!!! ;)

**Comment by Chomikmarkus** [comment]
But its getting flagged by 4 avs, my executable was before 3 from 26 after using EXOCET i get 4 from 26

**Comment by tanc7** [comment]
Yes, as Exocet grows in popularity, more AVs are catching it. That or,
people are submitting it to AV engines. I will be applying updates to
defeat AV again.

**Comment by Chomikmarkus** [comment]
Yes submitting it to virustotal, unfortunately! When planning any updates, ?

**Comment by tanc7** [comment]
I actually need some help because my personal and professional life is really tied up right now. If you don’t mind making commits that would be nice.
